### ISSUE TITLE
This does not work on Yosemite 

### ISSUE THREAD

**Issue by yc2prime** [cdraeger/alfred2-flushdns-workflow#1]
It is reported that "Error, cache was NOT flushed."

**Comment by cdraeger** [comment]
Thanks for letting me know, I haven't upgraded to Yosemite yet.

The new command for Yosemite seems to be `dscacheutil -flushcache` or `sudo discoveryutil mdnsflushcache`, so I'll have to test what will actually work. You may try to edit the command yourself, I will get to it as soon as I find the time to upgrade.

**Comment by timkelty** [comment]
I changed it to `sudo discoveryutil udnsflushcaches` and it works in Yosemite. `dscacheutil -flushcache` did not.

**Comment by cdraeger** [comment]
Thanks for the info! I still haven't upgraded to Yosemite for various reasons, but will still fix this as soon as I do (I'll probably want to have a check so the workflow works on all versions, 10.7+).

Anyone reading this can simply change the command manually via Alfred for now.

**Comment by xurizaemon** [comment]
On Yosemite, `sudo dscacheutil -flushcache` does appear to have worked for me, but I'd agree that without sudo it wouldn't have worked as noted above.

**Comment by xurizaemon** [comment]
NB: I don't pretend to understand what OSX DNS is doing today, if `dscacheutil` isn't right you should be able to use equivalent syntax to try multiple shell commands in order until one succeeds.

**Comment by cdraeger** [comment]
Thanks @xurizaemon, I still haven't upgraded. I'll check your changes 'soonish'. However, I am watching the development of this whole DNS mess since Yosemite, apparently Apple is about to switch back to `mDNSResponder`: http://9to5mac.com/2015/05/26/apple-drops-discoveryd-in-latest-os-x-beta-following-months-of-complaints-about-network-issues-with-yosemite/

There have been too many issues.. is this a workaround, or are they switching back for good? I don't know, but your PR looks like it can handle either situation. I'll get to it!

**Comment by xurizaemon** [comment]
Yeah, I don't know what their roadmap is, but this change is just shell syntax for "try killing `mDNSResponder`; if that doesn't work try `dscacheutil` refresh".

It preserves the existing default behaviour so should have no effect on your install, and then for new installs it'll realise that the old method didn't work and do the new.

Cheers
